const COLOUR_TO_FACE_TASK = {
  colours:[['Red','#D01F18'],['Yellow','#F2C230'],['Green','#2E8B57'],['Blue','#2F62C9'],['Purple','#7B3FA1'],['Grey','#919191']], emotions:['Happiness','Sadness','Anger','Fear','Disgust','Neutral'], index:0, selected:null, start:null,
  init(){this.index=0; STATE.logEvent(CONFIG.EVENT_TYPES.RESPONSE,{task_name:CONFIG.TASKS.COLOUR_TO_FACE,event:'task_initialized'}); this.renderCurrentItem();},
  faceSvg(label){return `<svg width="130" height="130" viewBox="0 0 180 180"><circle cx="90" cy="90" r="75" fill="#eee" stroke="#111" stroke-width="5"/><circle cx="65" cy="75" r="8"/><circle cx="115" cy="75" r="8"/><path d="M55 115 Q90 ${label==='Sadness'?95:135} 125 115" fill="none" stroke="#111" stroke-width="7" stroke-linecap="round"/></svg>`;},
  renderCurrentItem(){ if(this.index>=this.colours.length) return this.completeTask(); this.selected=null; this.start=new Date().toISOString(); const [name,hex]=this.colours[this.index]; document.getElementById('mainContent').innerHTML=`<section class="association-task" style="background:${hex};padding:30px;border-radius:8px"><div class="rating-panel"><h2>Colour-to-Face Association</h2><p>Which face best matches this colour?</p><div style="height:130px;background:${hex};border:3px solid #111;border-radius:8px;margin:20px 0"></div><p><strong>${name}</strong></p><div class="face-grid">${this.emotions.map(e=>`<button class="face-option" onclick="COLOUR_TO_FACE_TASK.choose('${e}')">${this.faceSvg(e)}<p>${e}</p></button>`).join('')}</div><div class="button-container"><button class="btn-success" onclick="COLOUR_TO_FACE_TASK.submitResponse()">Submit</button><button class="btn-warning" onclick="COLOUR_TO_FACE_TASK.skipItem()">Skip Item</button><button class="btn-secondary" onclick="COLOUR_TO_FACE_TASK.skipTask()">Skip Task</button><button class="btn-danger" onclick="NAVIGATION.stopTest()">Stop Test</button></div></div></section>`;},
  choose(e){this.selected=e; document.querySelectorAll('.face-option').forEach(b=>b.style.outline=''); event.currentTarget.style.outline='5px solid #ffc107';},
  submitResponse(){ if(!this.selected){alert('Select a face or skip.');return;} const now=new Date().toISOString(); const [name,hex]=this.colours[this.index]; STATE.logEvent(CONFIG.EVENT_TYPES.RESPONSE,{task_name:CONFIG.TASKS.COLOUR_TO_FACE,item_number:this.index+1,stimulus_colour:name,stimulus_hex:hex,selected_emotion:this.selected,response_time_ms:new Date(now)-new Date(this.start),trial_status:'completed'}); this.index++; this.renderCurrentItem();},
  skipItem(){STATE.logSkip(CONFIG.TASKS.COLOUR_TO_FACE,NAVIGATION.askSkipReason()); this.index++; this.renderCurrentItem();},
  skipTask(){STATE.logSkip(CONFIG.TASKS.COLOUR_TO_FACE,NAVIGATION.askSkipReason()); this.completeTask();},
  pause(){NAVIGATION.pause();}, resume(){NAVIGATION.resume();}, completeTask(){STATE.logEvent(CONFIG.EVENT_TYPES.COMPLETE,{task_name:CONFIG.TASKS.COLOUR_TO_FACE}); STORAGE.autoSave(); NAVIGATION.nextPage();}
};
