const INDIAN_MEMORY_TASK = {
  culturalColours: [
    {id:'IC01', name:'Kumkum red', L:45, a:65, b:50, hex:'#D01F18'},
    {id:'IC02', name:'Haldi yellow', L:85, a:-15, b:85, hex:'#F2C230'},
    {id:'IC03', name:'Kesari / saffron', L:65, a:35, b:70, hex:'#FF8C1A'},
    {id:'IC04', name:'Marigold orange', L:75, a:40, b:65, hex:'#F59E18'},
    {id:'IC05', name:'Mehendi green-brown', L:40, a:-25, b:30, hex:'#6B7B3A'},
    {id:'IC06', name:'Indigo / neel', L:25, a:15, b:-45, hex:'#263B8C'},
    {id:'IC07', name:'Peacock blue-green', L:45, a:-20, b:-35, hex:'#008C8C'},
    {id:'IC08', name:'Chandan beige', L:70, a:10, b:25, hex:'#D8B782'},
    {id:'IC09', name:'Terracotta / mitti brown', L:50, a:30, b:35, hex:'#A75C36'},
    {id:'IC10', name:'Jasmine white', L:95, a:-2, b:5, hex:'#F6F0DD'}
  ],
  categories: ['Family/person','Friend/community','Home','Village/town','Temple/religious place','Hospital/clinic','School/workplace','Festival','Marriage/family ceremony','Religious ritual','Childhood event','Clothing/textile','Jewellery/decoration','Household object','Art/media','Food/spice/kitchen','Cosmetics/body decoration','Medicine/health','Flowers/plants','Animals/birds','Water/pond/river/sea','Sky/night','Land/soil','Summer','Monsoon/rain','Winter','Morning/evening/night','No memory','Not sure','Other'],
  index:0, start:null,
  init(){this.index=0; STATE.logEvent(CONFIG.EVENT_TYPES.RESPONSE,{task_name:CONFIG.TASKS.MEMORY,event:'task_initialized'}); this.renderCurrentItem();},
  renderCurrentItem(){ if(this.index>=this.culturalColours.length) return this.completeTask(); const c=this.culturalColours[this.index]; this.start=new Date().toISOString(); document.getElementById('mainContent').innerHTML=`<section class="scientific-page" style="background:${c.hex};padding:24px;border-radius:8px"><div class="rating-panel"><h2>Indian Chromatic Memory</h2><p>Colour ${this.index+1} of ${this.culturalColours.length}</p><div style="height:160px;background:${c.hex};border:3px solid #111;border-radius:8px;margin:20px 0"></div><p><strong>${c.name}</strong><br><small>Provisional CIELAB: L*=${c.L}, a*=${c.a}, b*=${c.b}; HEX ${c.hex}</small></p><div class="form-group"><label>Is this colour familiar?</label><select id="familiar"><option value="">Select</option><option>Yes</option><option>No</option><option>Not sure</option></select></div><div class="form-group"><label>Does it remind you of anything?</label><select id="reminds"><option value="">Select</option><option>Yes</option><option>No</option><option>Not sure</option></select></div><div class="form-group"><label>What does it remind you of?</label><select id="memoryCategory" onchange="document.getElementById('otherMemoryWrap').style.display=this.value==='Other'?'block':'none'"><option value="">Select</option>${this.categories.map(x=>`<option>${x}</option>`).join('')}</select></div><div id="otherMemoryWrap" class="form-group" style="display:none"><label>Other memory description</label><input id="otherMemory" type="text"></div><div class="form-group"><label>How does this colour feel?</label><select id="memoryValence"><option value="">Select</option><option>Pleasant</option><option>Neutral</option><option>Unpleasant</option></select></div><div class="button-container"><button class="btn-success" onclick="INDIAN_MEMORY_TASK.submitResponse()">Submit</button><button class="btn-warning" onclick="INDIAN_MEMORY_TASK.skipColour()">Skip Colour</button><button class="btn-secondary" onclick="INDIAN_MEMORY_TASK.skipTask()">Skip Task</button><button class="btn-danger" onclick="NAVIGATION.stopTest()">Stop Test</button></div></div></section>`;},
  submitResponse(){ const fam=document.getElementById('familiar').value, rem=document.getElementById('reminds').value, cat=document.getElementById('memoryCategory').value, val=document.getElementById('memoryValence').value; if(!fam||!rem||!cat||!val){alert('Please answer all questions or skip.');return;} const c=this.culturalColours[this.index]; const now=new Date().toISOString(); STATE.logEvent(CONFIG.EVENT_TYPES.RESPONSE,{task_name:CONFIG.TASKS.MEMORY,colour_number:this.index+1,stimulus_id:c.id,stimulus_name:c.name,cielab_L:c.L,cielab_a:c.a,cielab_b:c.b,hex_value:c.hex,familiarity:fam,reminds:rem,memory_category:cat,memory_other_text:document.getElementById('otherMemory').value,valence_response:val,response_time_ms:new Date(now)-new Date(this.start),trial_status:'completed'}); this.index++; this.renderCurrentItem();},
  skipColour(){ const c=this.culturalColours[this.index]; STATE.logSkip(CONFIG.TASKS.MEMORY,NAVIGATION.askSkipReason()); STATE.logEvent(CONFIG.EVENT_TYPES.SKIP,{task_name:CONFIG.TASKS.MEMORY,stimulus_id:c.id,stimulus_name:c.name,trial_status:'skipped',skip_status:'skipped'}); this.index++; this.renderCurrentItem();},
  skipTask(){STATE.logSkip(CONFIG.TASKS.MEMORY,NAVIGATION.askSkipReason()); this.completeTask();},
  pause(){NAVIGATION.pause();}, resume(){NAVIGATION.resume();}, completeTask(){STATE.logEvent(CONFIG.EVENT_TYPES.COMPLETE,{task_name:CONFIG.TASKS.MEMORY}); STORAGE.autoSave(); NAVIGATION.nextPage();}
};
